const ON_LOAD = 'ON_LOAD'
    , ON_FAILURE = 'ON_FAILURE'
    , ON_SUCCESS = 'ON_SUCCESS'
    , ON_HOME_HIDE = 'ON_HOME_HIDE'
    , ON_HOME_LOAD_START = 'ON_HOME_LOAD_START'
    , ON_HOME_LOAD_FAILURE = 'ON_HOME_LOAD_FAILURE'
    , ON_HOME_LOAD_SUCCESS = 'ON_HOME_LOAD_SUCCESS'
    , ON_HOME_PLAY_VOICE = 'ON_HOME_PLAY_VOICE'
    , ON_HOME_STOP_VOICE = 'ON_HOME_STOP_VOICE'
    , ON_RECORD_START = 'ON_RECORD_START'
    , ON_RECORD_STOP = 'ON_RECORD_STOP'
    , ON_RECORD_ERROR = 'ON_RECORD_ERROR'
    , ON_RECORD_SUCCESS = 'ON_RECORD_SUCCESS'
    , ON_RECORD_COUNT = 'ON_RECORD_COUNT'
    , ON_RECORD_PLAY_COUNT = 'ON_RECORD_PLAY_COUNT'
    , ON_RECORD_PLAY = 'ON_RECORD_PLAY'
    , ON_RECORD_PAUSE = 'ON_RECORD_PAUSE'
    , ON_RECORD_FINISH = 'ON_RECORD_FINISH'
    , ON_RECORD_RADIO_CHANGE = 'ON_RECORD_RADIO_CHANGE'
    , ON_RECORD_SUBMIT_START = 'ON_RECORD_SUBMIT_START'
    , ON_RECORD_SUBMIT_SUCCESS = 'ON_RECORD_SUBMIT_SUCCESS'
    , ON_RECORD_SUBMIT_FAILURE = 'ON_RECORD_SUBMIT_FAILURE'
    , ON_RECORD_SWITCH_SHOW = 'ON_RECORD_SWITCH_SHOW'
    , ON_LOGIN_START = 'ON_LOGIN_START'
    , ON_LOGIN_SUCCESS = 'ON_LOGIN_SUCCESS'
    , ON_LOGIN_FAILURE = 'ON_LOGIN_FAILURE'
    , ON_SESSION_START = 'ON_SESSION_START'
    , ON_SESSION_SUCCESS = 'ON_SESSION_SUCCESS'
    , ON_SESSION_FAILURE = 'ON_SESSION_FAILURE'

export  {
   ON_LOAD, 
   ON_FAILURE,
   ON_SUCCESS,
   ON_HOME_HIDE,
   ON_HOME_LOAD_START, 
   ON_HOME_LOAD_FAILURE,
   ON_HOME_LOAD_SUCCESS,
   ON_HOME_PLAY_VOICE,
   ON_HOME_STOP_VOICE,
   ON_RECORD_ERROR,
   ON_RECORD_START,
   ON_RECORD_STOP,
   ON_RECORD_SUCCESS,
   ON_RECORD_COUNT,
   ON_RECORD_PLAY_COUNT,
   ON_RECORD_PLAY,
   ON_RECORD_PAUSE,
   ON_RECORD_FINISH,
   ON_RECORD_RADIO_CHANGE,
   ON_RECORD_SUBMIT_START,
   ON_RECORD_SUBMIT_SUCCESS,
   ON_RECORD_SUBMIT_FAILURE,
   ON_RECORD_SWITCH_SHOW,
   ON_LOGIN_START,
   ON_LOGIN_SUCCESS,
   ON_LOGIN_FAILURE,
   ON_SESSION_START,
   ON_SESSION_SUCCESS,
   ON_SESSION_FAILURE,
}